--- 
after_success: 
  - "bash <(curl -s https://codecov.io/bash)"
  - "mvn sonar:sonar -P sonar"
cache: 
  directories: 
    - $HOME/.m2
install: true
jdk: oraclejdk8
language: java
script: "mvn clean install"
sudo: false
